### PR TITLE
Update to follow Guard 2.0 changes

### PR DESCRIPTION
**Pull request by ezekg**
With this change, I fixed an issue with the watcher, s you no longer need the `watch` line in the template file because it will automatically watch the input file.

``` ruby
# This
guard 'uglify', :input => 'app/assets/javascripts/application.js', :output => "public/javascripts/application.js" do
  watch (%r{app/assets/javascripts/application.js})
end

# Can be changed to this
guard 'uglify',
  :input => 'app/assets/javascripts/application.js',
  :output => "public/javascripts/application.js"
```

### CODE REVIEW

**Comment by mraaroncruz** [comment]
Thanks a lot. Could you also add something similar to your message here to the README? Do you want commit access?

**Comment by ezekg** [comment]
Done. I'd love commit access.

**Comment by mraaroncruz** [comment]
I'll give it to you and merge and push in the morning

**Comment by ezekg** [comment]
Okay, I went ahead and rewrote a lot of the plugin for better performance and more options. Added a `:uglifier` option that is passed to the Uglifier gem, so that you can customize the output better. Hope that's cool. Added some simple tests as well.

**Comment by ezekg** [comment]
Been running this in our development stack for a couple days and it's working great. Let me know when you merge it or give me commit access. I'd also be down to take over the rubygem, since I know you don't use this project any longer. That way I can keep this updated.

**Pull request merged**
